# Generated by Django 5.0.2 on 2024-02-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
