# Generated by Django 5.0.2 on 2024-02-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduHub', '0002_student_stud_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
